import { createContext, useContext } from 'react';

export const dark = {
  pageBg:             "#0F1117",
  sidebarBg:          "#161B27",
  sidebarBorder:      "#1E2A3D",
  cardBg:             "#1A2035",
  cardBorder:         "#1E2A3D",
  kpiGradient:        "linear-gradient(135deg,#1A2035 0%,#162440 100%)",
  textPrimary:        "#FFFFFF",
  textSecondary:      "#9CA3AF",
  textTertiary:       "#6B7280",
  navActiveBg:        "#1E3A5F",
  navActiveText:      "#FFFFFF",
  navActiveIcon:      "#3B82F6",
  navInactiveText:    "#9CA3AF",
  navInactiveIcon:    "#6B7280",
  mNavActiveBg:       "#3B82F620",
  deviceOnBg:         "#0D1F35",
  deviceOnBorder:     "#1E3A5F",
  deviceOffBg:        "#151C2C",
  deviceOffBorder:    "#1E2535",
  deviceOffDot:       "#374151",
  deviceOffText:      "#4B5563",
  ruleItemBg:         "#1A2035",
  ruleIconBg:         "#0F1117",
  ruleIconActiveBg:   "#0D2030",
  ruleIconInactiveBg: "#1A2035",
  badgeKpiBg:         "#0D2818",
  badgeKpiColor:      "#10B981",
  badgeActiveBg:      "#0D2818",
  badgeActiveColor:   "#10B981",
  badgeInactiveBg:    "#1F2937",
  badgeInactiveColor: "#6B7280",
  barTrack:           "#1E2D45",
  chartGridline:      "#1E2A3D",
  chartAxisText:      "#6B7280",
  legendText:         "#9CA3AF",
  legendValue:        "#D1D5DB",
  pillBg:             "#1E2D45",
  pillBorder:         "#2D3D55",
  toggleOffBg:        "#374151",
  alertIconBg:        "#2D1F00",
  bellBg:             "#1A2035",
  bellBorder:         "#1E2A3D",
  alertBg:            "#1A2035",
  consumoText:        "#64748B",
  efficiencyBg:       "#1A2035",
  mKpiGrad:           ["#1E3A5F","#1A1F35","#1A3328","#2D2010"] as string[],
  divider:            "#1E2D45",
  statLabel:          "#64748B",
  dateBadgeBg:        "#1A2035",
  dateBadgeText:      "#94A3B8",
  deviceIconBg:       "#161B27",
  logoBg:             "#161B27",
};

export const light: typeof dark = {
  pageBg:             "#F1F5F9",
  sidebarBg:          "#F1F5F9",
  sidebarBorder:      "#E2E8F0",
  cardBg:             "#FFFFFF",
  cardBorder:         "#E2E8F0",
  kpiGradient:        "linear-gradient(135deg,#FFFFFF 0%,#EFF6FF 100%)",
  textPrimary:        "#111827",
  textSecondary:      "#6B7280",
  textTertiary:       "#94A3B8",
  navActiveBg:        "#EFF6FF",
  navActiveText:      "#1D4ED8",
  navActiveIcon:      "#3B82F6",
  navInactiveText:    "#6B7280",
  navInactiveIcon:    "#9CA3AF",
  mNavActiveBg:       "#DBEAFE",
  deviceOnBg:         "#EFF6FF",
  deviceOnBorder:     "#BFDBFE",
  deviceOffBg:        "#F9FAFB",
  deviceOffBorder:    "#E5E7EB",
  deviceOffDot:       "#CBD5E1",
  deviceOffText:      "#9CA3AF",
  ruleItemBg:         "#F8FAFC",
  ruleIconBg:         "#F3F4F6",
  ruleIconActiveBg:   "#DBEAFE",
  ruleIconInactiveBg: "#F3F4F6",
  badgeKpiBg:         "#DCFCE7",
  badgeKpiColor:      "#059669",
  badgeActiveBg:      "#DCFCE7",
  badgeActiveColor:   "#059669",
  badgeInactiveBg:    "#F3F4F6",
  badgeInactiveColor: "#9CA3AF",
  barTrack:           "#E2E8F0",
  chartGridline:      "#E2E8F0",
  chartAxisText:      "#9CA3AF",
  legendText:         "#6B7280",
  legendValue:        "#374151",
  pillBg:             "#FEF9C3",
  pillBorder:         "#FDE68A",
  toggleOffBg:        "#CBD5E1",
  alertIconBg:        "#FEF3C7",
  bellBg:             "#FFFFFF",
  bellBorder:         "#E2E8F0",
  alertBg:            "#FFFFFF",
  consumoText:        "#94A3B8",
  efficiencyBg:       "#F0FDF4",
  mKpiGrad:           ["#DBEAFE","#EFF6FF","#DCFCE7","#FEF3C7"] as string[],
  divider:            "#E2E8F0",
  statLabel:          "#94A3B8",
  dateBadgeBg:        "#F1F5F9",
  dateBadgeText:      "#6B7280",
  deviceIconBg:       "#F3F4F6",
  logoBg:             "#FFFFFF",
};

export type Theme = typeof dark;
export type AppPage = 'dashboard' | 'devices' | 'reports' | 'rules';
export const pageToPath: Record<AppPage, string> = {
  dashboard:    '/',
  devices:      '/dispositivos',
  reports:      '/reportes',
  rules:        '/reglas',
};
export const ThemeCtx = createContext<Theme>(dark);
export const useT = () => useContext(ThemeCtx);

export type ThemeToggleCtx = { isDark: boolean; toggle: () => void };
export const ThemeToggleCtx = createContext<ThemeToggleCtx>({ isDark: true, toggle: () => {} });
export const useThemeToggle = () => useContext(ThemeToggleCtx);
